package com.book.dao;

import org.apache.ibatis.annotations.Mapper;

import com.book.entity.LentManage;

@Mapper
public interface LentManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lent_manage
     *
     * @mbg.generated Thu Dec 14 11:49:28 JST 2023
     */
    int deleteByPrimaryKey(Integer lentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lent_manage
     *
     * @mbg.generated Thu Dec 14 11:49:28 JST 2023
     */
    int insert(LentManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lent_manage
     *
     * @mbg.generated Thu Dec 14 11:49:28 JST 2023
     */
    int insertSelective(LentManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lent_manage
     *
     * @mbg.generated Thu Dec 14 11:49:28 JST 2023
     */
    LentManage selectByPrimaryKey(Integer lentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lent_manage
     *
     * @mbg.generated Thu Dec 14 11:49:28 JST 2023
     */
    int updateByPrimaryKeySelective(LentManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lent_manage
     *
     * @mbg.generated Thu Dec 14 11:49:28 JST 2023
     */
    int updateByPrimaryKey(LentManage record);
    
}