package com.book.dao;

import com.book.entity.LentRecords;

public interface LentRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lent_records
     *
     * @mbg.generated Fri Dec 15 11:43:24 JST 2023
     */
    int deleteByPrimaryKey(Integer lentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lent_records
     *
     * @mbg.generated Fri Dec 15 11:43:24 JST 2023
     */
    int insert(LentRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lent_records
     *
     * @mbg.generated Fri Dec 15 11:43:24 JST 2023
     */
    int insertSelective(LentRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lent_records
     *
     * @mbg.generated Fri Dec 15 11:43:24 JST 2023
     */
    LentRecords selectByPrimaryKey(Integer lentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lent_records
     *
     * @mbg.generated Fri Dec 15 11:43:24 JST 2023
     */
    int updateByPrimaryKeySelective(LentRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lent_records
     *
     * @mbg.generated Fri Dec 15 11:43:24 JST 2023
     */
    int updateByPrimaryKey(LentRecords record);
}