package com.book.entity;

import java.io.Serializable;

import lombok.Data;

@Data
public class LoginUser implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginuser.USER_NAME
     *
     * @mbg.generated Wed Dec 06 11:03:32 JST 2023
     */
    private Integer userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginuser.PASSWORD
     *
     * @mbg.generated Wed Dec 06 11:03:32 JST 2023
     */
    private String password;
}