package com.book.entity;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;

@Data
public class MstBook implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_book.BOOK_ID
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_book.TITLE
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_book.PUBLISHER
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private String publisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_book.AUTHOR
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_book.GENRE1
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Integer genre1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_book.GENRE2
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Integer genre2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_book.LENDING_FLAG
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Integer lendingFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_book.CREATE_DATE
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_book.UPDATE_DATE
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_book.DELETE_FLAG
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Integer deleteFlag;

}