package com.book.entity;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;

@Data
public class UserInfo implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_ID
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.PASSWORD
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_NAME
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.DEPARTMENT
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    private Integer department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.CREATE_DATE
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.UPDATE_DATE
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.DELETE_FLAG
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    private Integer deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USER_ID
     *
     * @return the value of user_info.USER_ID
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USER_ID
     *
     * @param userId the value for user_info.USER_ID
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.PASSWORD
     *
     * @return the value of user_info.PASSWORD
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.PASSWORD
     *
     * @param password the value for user_info.PASSWORD
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USER_NAME
     *
     * @return the value of user_info.USER_NAME
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USER_NAME
     *
     * @param userName the value for user_info.USER_NAME
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.DEPARTMENT
     *
     * @return the value of user_info.DEPARTMENT
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    public Integer getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.DEPARTMENT
     *
     * @param department the value for user_info.DEPARTMENT
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    public void setDepartment(Integer department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.CREATE_DATE
     *
     * @return the value of user_info.CREATE_DATE
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.CREATE_DATE
     *
     * @param createDate the value for user_info.CREATE_DATE
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.UPDATE_DATE
     *
     * @return the value of user_info.UPDATE_DATE
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.UPDATE_DATE
     *
     * @param updateDate the value for user_info.UPDATE_DATE
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.DELETE_FLAG
     *
     * @return the value of user_info.DELETE_FLAG
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.DELETE_FLAG
     *
     * @param deleteFlag the value for user_info.DELETE_FLAG
     *
     * @mbg.generated Tue Dec 12 15:09:54 JST 2023
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}