package com.book.entity;

import java.util.Date;

import lombok.Data;

@Data
public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_ID
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_NAME
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.DEPARTMENT
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Integer department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.CREATE_DATE
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.UPDATE_DATE
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.DELETE_FLAG
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Integer deleteFlag;
}