package com.book.entity;

import java.util.Date;

import lombok.Data;

@Data
public class LentManage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lent_manage.LENT_NUMBER
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Integer lentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lent_manage.BOOK_ID
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lent_manage.USER_ID
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lent_manage.LENTDATE
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Date lentdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lent_manage.RETURNDATE
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Date returndate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lent_manage.LENTFLAG
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Integer lentflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lent_manage.CREATE_DATE
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lent_manage.UPDATE_DATE
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lent_manage.DELETE_FLAG
     *
     * @mbg.generated Tue Dec 05 16:43:51 JST 2023
     */
    private Integer deleteFlag;

}